package uk.ac.aber.dcs.cs221.n15.Controller;

public enum RequestType {
	FRIEND_REQUEST,
	ACCEPT_FRIENDSHIP,
	DECLINE_FRIENDSHIP,
	OFFER_FIGHT,
	ACCEPT_FIGHT,
	DECLINE_FIGHT,
	ACCEPT_BREED_OFFER,
	BREEDING_RESOLVED,
	BUY_MONSTER;
	
}
