package uk.ac.aber.dcs.cs221.n15.Controller;

public enum RequestType {
	FRIEND_REQUEST,
	ACCEPTED_FRIENDSHIP,
	DECLINED_FRIENDSHIP,
	OFFER_FIGHT,
	ACCEPTED_FIGHT,
	DECLINED_FIGHT,
	ACCEPT_BREED_OFFER,
	BREEDING_RESOLVED,
	BUY_MONSTER;
	
}
